preload = ~/.config/backgrounds/lake_district.jpg

# the , would have something before it specifying what screen the bg should be on
# if there's nothing there, it applies the image to all screens
wallpaper = , ~/.config/backgrounds/lake_district.jpg 
